// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js

import * as activateprofileModule from './ActivateProfile/ActivateProfile'
import * as alertModule from './Alert/Alert'
import * as alexaModule from './Alexa/Alexa'
import * as homeassistantModule from './HomeAssistant/HomeAssistant'
import * as keyboardModule from './Keyboard/Keyboard'
import * as ledfxModule from './LedFx/LedFx'
import * as midimModule from './MidiM/MidiM'
import * as mpfacedetectModule from './MpFaceDetect/MpFaceDetect'
import * as mpfacemeshModule from './MpFaceMesh/MpFaceMesh'
import * as mphandsModule from './MpHands/MpHands'
import * as mpholisticModule from './MpHolistic/MpHolistic'
import * as mpobjectronModule from './MpObjectron/MpObjectron'
import * as mpposeModule from './MpPose/MpPose'
import * as mqttmModule from './MqttM/MqttM'
import * as playsoundModule from './PlaySound/PlaySound'
import * as restmModule from './RestM/RestM'
import * as sayModule from './Say/Say'
import * as shellModule from './Shell/Shell'
import * as timeModule from './Time/Time'
import * as wledModule from './Wled/Wled'

export default {
  [activateprofileModule.id]: activateprofileModule,
  [alertModule.id]: alertModule,
  [alexaModule.id]: alexaModule,
  [homeassistantModule.id]: homeassistantModule,
  [keyboardModule.id]: keyboardModule,
  [ledfxModule.id]: ledfxModule,
  [midimModule.id]: midimModule,
  [mpfacedetectModule.id]: mpfacedetectModule,
  [mpfacemeshModule.id]: mpfacemeshModule,
  [mphandsModule.id]: mphandsModule,
  [mpholisticModule.id]: mpholisticModule,
  [mpobjectronModule.id]: mpobjectronModule,
  [mpposeModule.id]: mpposeModule,
  [mqttmModule.id]: mqttmModule,
  [playsoundModule.id]: playsoundModule,
  [restmModule.id]: restmModule,
  [sayModule.id]: sayModule,
  [shellModule.id]: shellModule,
  [timeModule.id]: timeModule,
  [wledModule.id]: wledModule
}
