// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js

import * as activateprofileModule from './ActivateProfile/ActivateProfile'
import * as alertModule from './Alert/Alert'
import * as alexaModule from './Alexa/Alexa'
import * as gamepadModule from './Gamepad/Gamepad'
import * as homeassistantModule from './HomeAssistant/HomeAssistant'
import * as keyboardModule from './Keyboard/Keyboard'
import * as ledfxModule from './LedFx/LedFx'
import * as midiModule from './Midi/Midi'
import * as mpfacedetectModule from './MpFaceDetect/MpFaceDetect'
import * as mpfacemeshModule from './MpFaceMesh/MpFaceMesh'
import * as mphandsModule from './MpHands/MpHands'
import * as mpholisticModule from './MpHolistic/MpHolistic'
import * as mpobjectronModule from './MpObjectron/MpObjectron'
import * as mpposeModule from './MpPose/MpPose'
import * as mqttModule from './Mqtt/Mqtt'
import * as playsoundModule from './PlaySound/PlaySound'
import * as restModule from './Rest/Rest'
import * as sayModule from './Say/Say'
import * as shellModule from './Shell/Shell'
import * as timeModule from './Time/Time'
import * as wledModule from './Wled/Wled'

export default {
  [activateprofileModule.id]: activateprofileModule,
  [alertModule.id]: alertModule,
  [alexaModule.id]: alexaModule,
  [gamepadModule.id]: gamepadModule,
  [homeassistantModule.id]: homeassistantModule,
  [keyboardModule.id]: keyboardModule,
  [ledfxModule.id]: ledfxModule,
  [midiModule.id]: midiModule,
  [mpfacedetectModule.id]: mpfacedetectModule,
  [mpfacemeshModule.id]: mpfacemeshModule,
  [mphandsModule.id]: mphandsModule,
  [mpholisticModule.id]: mpholisticModule,
  [mpobjectronModule.id]: mpobjectronModule,
  [mpposeModule.id]: mpposeModule,
  [mqttModule.id]: mqttModule,
  [playsoundModule.id]: playsoundModule,
  [restModule.id]: restModule,
  [sayModule.id]: sayModule,
  [shellModule.id]: shellModule,
  [timeModule.id]: timeModule,
  [wledModule.id]: wledModule
}
