// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js
// @ts-nocheck

import * as alertModule from './Alert/Alert.js'
import * as alexaModule from './Alexa/Alexa.js'
import * as homeassistantModule from './HomeAssistant/HomeAssistant.js'
import * as keyboardModule from './Keyboard/Keyboard.js'
import * as ledfxModule from './LedFx/LedFx.js'
import * as midiModule from './MIDI/MIDI.js'
import * as mpfacedetectModule from './MpFaceDetect/MpFaceDetect.js'
import * as mpfacemeshModule from './MpFaceMesh/MpFaceMesh.js'
import * as mphandsModule from './MpHands/MpHands.js'
import * as mpholisticModule from './MpHolistic/MpHolistic.js'
import * as mpobjectronModule from './MpObjectron/MpObjectron.js'
import * as mpposeModule from './MpPose/MpPose.js'
import * as mqttModule from './MQTT/MQTT.js'
import * as restModule from './REST/REST.js'
import * as sayModule from './Say/Say.js'
import * as shellModule from './Shell/Shell.js'
import * as wledModule from './Wled/Wled.js'

export default {
  [alertModule.id]: alertModule,
  [alexaModule.id]: alexaModule,
  [homeassistantModule.id]: homeassistantModule,
  [keyboardModule.id]: keyboardModule,
  [ledfxModule.id]: ledfxModule,
  [midiModule.id]: midiModule,
  [mpfacedetectModule.id]: mpfacedetectModule,
  [mpfacemeshModule.id]: mpfacemeshModule,
  [mphandsModule.id]: mphandsModule,
  [mpholisticModule.id]: mpholisticModule,
  [mpobjectronModule.id]: mpobjectronModule,
  [mpposeModule.id]: mpposeModule,
  [mqttModule.id]: mqttModule,
  [restModule.id]: restModule,
  [sayModule.id]: sayModule,
  [shellModule.id]: shellModule,
  [wledModule.id]: wledModule
}
