// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js

import type { IOMainModulePart } from '../../../shared/types.js'
import alexaMain from './Alexa/Alexa.main.js'
import keyboardMain from './Keyboard/Keyboard.main.js'
import shellMain from './Shell/Shell.main.js'

export const mainModuleHandlers: IOMainModulePart[] = [alexaMain, keyboardMain, shellMain]
