// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js

import type { IOMainModulePart } from '../../../shared/types'
import alexaMain from './Alexa/Alexa.main'
import keyboardMain from './Keyboard/Keyboard.main'
import mqttMain from './MQTT/MQTT.main'
import restMain from './REST/REST.main'
import shellMain from './Shell/Shell.main'

export const mainModuleHandlers: IOMainModulePart[] = [
  alexaMain,
  keyboardMain,
  mqttMain,
  restMain,
  shellMain
]
