// src/renderer/src/modules/REST/REST.types.ts

// --- Simple Input Field Definition for Blueprints ---
export type SimpleInputFieldValue = string | number | boolean // Extend as needed (e.g. string[])

export interface SimpleInputField {
  id: string // Unique ID for this input within the Blueprint (e.g., 'repoPath', 'targetUser')
  label: string // User-friendly label shown in the simple form (e.g., "GitHub Repository Path")
  type: 'text' | 'url' | 'number' | 'boolean' | 'select' // Type of input
  defaultValue?: SimpleInputFieldValue
  options?: Array<{ label: string; value: SimpleInputFieldValue }> // For 'select' type
  required?: boolean
  helpText?: string // Additional guidance for the user
  placeholder?: string // Placeholder for text/url/number inputs
}

// --- REST Preset Definition (Generated by Blueprints or created manually) ---
export interface RestPresetDefinition {
  id: string // uuid for the preset itself
  name: string // Name of the preset (can be generated by Blueprint, e.g., "Stats for {{repoPath}}")
  icon?: string // Icon for the preset (can be generated)
  description?: string // Description for the preset (can be generated)

  // Core REST Call details (these will contain actual values after Blueprint processing)
  url: string
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS' | 'HEAD'
  headers?: Record<string, string>
  bodyTemplate?: string // Actual body string for the preset (JSON string, XML, etc.)
}

// --- Blueprint Definition (The template for generating a REST Preset) ---
export interface BlueprintDefinition {
  id: string // Unique ID for the Blueprint definition (e.g., 'github-stats-v1')
  name: string // User-friendly name of the Blueprint (e.g., "GitHub Repo Stats Fetcher")
  description: string // What this Blueprint does
  icon?: string // Icon for the Blueprint in selection lists
  creatorInfo?: { name: string; contact?: string } // Optional attribution

  simpleInputs: SimpleInputField[] // Array of simple input fields user will fill

  // Template for the REST Preset that will be generated.
  // Fields here can contain placeholders like {{blueprintInput.inputId}}
  presetTemplate: {
    nameTemplate: string // e.g., "Stats for {{blueprintInput.repoPath}}"
    iconTemplate?: string // e.g., "mdi:github" or "{{blueprintInput.iconChoice}}"
    descriptionTemplate?: string // e.g., "Fetches latest release for {{blueprintInput.repoPath}}"

    // Template for the core REST call details
    urlTemplate: string // e.g., "https://api.github.com/repos/{{blueprintInput.repoPath}}/releases/latest"
    method: RestPresetDefinition['method'] // Usually fixed for a given Blueprint
    headersTemplate?: Record<string, string> // e.g., { "Authorization": "Bearer {{blueprintInput.token}}" }
    bodyTemplateTemplate?: string // e.g., "{ \"user\": \"{{blueprintInput.username}}\" }"
  }
}

// --- Custom Configuration for the REST Module ---
export interface RestModuleCustomConfig {
  presets: RestPresetDefinition[]
  blueprints: BlueprintDefinition[] // User-imported and bundled blueprints
}

// --- Data for a REST Output Row ---
export interface RestOutputRowData {
  label?: string // User-defined label for this specific row instance
  host: string // URL for this specific row instance
  options: {
    method: RestPresetDefinition['method']
    headers?: Record<string, string>
    body?: string // Stringified JSON body for this specific row instance
  }

  // Blueprint linkage for simplified editing
  blueprintIdUsed?: string // ID of the BlueprintDefinition used to create/configure this
  blueprintInputsSnapshot?: Record<string, SimpleInputFieldValue> // Snapshot of simple inputs
}

// --- IPC Arguments ---
export interface RestRequestArgs {
  url: string
  method?: RestPresetDefinition['method']
  headers?: Record<string, string>
  body?: string
}
