import { BlueprintDefinition } from '../RestM.types'

export const exampleGitHubStatsBlueprint: BlueprintDefinition = {
  id: 'bp_github_repo_stats_v1', // Unique ID for this blueprint
  name: 'GitHub Repository Latest Release Info',
  description:
    'Creates a preset to fetch the latest release information for a public GitHub repository.',
  icon: 'mdi:github',
  creatorInfo: { name: 'IO Bundled Blueprints' },
  simpleInputs: [
    {
      id: 'repoPath',
      label: 'Repository Path (e.g., owner/repo)',
      type: 'text', // Could be 'url' but 'text' is fine for path
      required: true,
      placeholder: 'YeonV/io',
      helpText: 'Enter the full path like "facebook/react" or "microsoft/vscode".'
    }
  ],
  presetTemplate: {
    nameTemplate: 'GitHub: {{blueprintInput.repoPath}} Latest Release', // Generated Preset Name
    iconTemplate: 'mdi:github', // Fixed icon for presets generated by this
    descriptionTemplate:
      'Fetches latest release data for the GitHub repository: {{blueprintInput.repoPath}}.',
    urlTemplate: 'https://api.github.com/repos/{{blueprintInput.repoPath}}/releases/latest',
    method: 'GET',
    headersTemplate: {
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'IO-App-Blueprint-Requester' // Good practice to set a User-Agent
    }
    // bodyTemplateTemplate is undefined for GET
  }
}
