// THIS FILE IS AUTO-GENERATED BY scripts/sync-integrations.js

import type { IOMainIntegrationPart } from '../../../shared/integration-types'

import homeAssistantMainPart from './HomeAssistant/HomeAssistant.main'

export const mainIntegrationHandlers: IOMainIntegrationPart[] = [homeAssistantMainPart]
