// THIS FILE IS AUTO-GENERATED BY scripts/sync-integrations.js

/* eslint-disable prettier/prettier */

import type { FullIntegrationDefinition, IntegrationId } from '../../../shared/integration-types'

import { default as HomeAssistantSettingsComponent, integrationConfig as homeAssistantConfig } from './HomeAssistant/HomeAssistant.settings'

export const integrationsList: FullIntegrationDefinition[] = [
  { ...homeAssistantConfig, SettingsComponent: HomeAssistantSettingsComponent }
]

export const integrationsMap: Record<IntegrationId, FullIntegrationDefinition> = {
  [homeAssistantConfig.id]: { ...homeAssistantConfig, SettingsComponent: HomeAssistantSettingsComponent }
}
