// THIS FILE IS AUTO-GENERATED BY scripts/sync-integrations.js

/* eslint-disable prettier/prettier */

export type IntegrationId =
  | 'home-assistant'

export const ALL_INTEGRATION_IDS: IntegrationId[] = [
  'home-assistant'
]
