// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js

export type ModuleId =
  | 'activateprofile-module'
  | 'alert-module'
  | 'alexa-module'
  | 'homeassistant-module'
  | 'keyboard-module'
  | 'ledfx-module'
  | 'midi-module'
  | 'mpfacedetect-module'
  | 'mpfacemesh-module'
  | 'mphands-module'
  | 'mpholistic-module'
  | 'mpobjectron-module'
  | 'mppose-module'
  | 'mqtt-module'
  | 'rest-module'
  | 'say-module'
  | 'shell-module'
  | 'time-module'
  | 'wled-module'

export const ALL_MODULE_IDS: ModuleId[] = [
  'activateprofile-module',
  'alert-module',
  'alexa-module',
  'homeassistant-module',
  'keyboard-module',
  'ledfx-module',
  'midi-module',
  'mpfacedetect-module',
  'mpfacemesh-module',
  'mphands-module',
  'mpholistic-module',
  'mpobjectron-module',
  'mppose-module',
  'mqtt-module',
  'rest-module',
  'say-module',
  'shell-module',
  'time-module',
  'wled-module'
]
