// scripts/sync-modules.js
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const rendererModulesBaseDir = path.join(__dirname, '../src/renderer/src/modules')
// Assuming main-side logic files are co-located for this script version:
// e.g., src/renderer/src/modules/Alexa/Alexa.main.ts

const rendererModulesRegistryPath = path.join(rendererModulesBaseDir, 'modules.ts')
const mainProcessModulesRegistryPath = path.join(rendererModulesBaseDir, 'modules.main.ts')

let rendererImportsArray = []
let rendererExportsArray = []
let mainRegistryImportsArray = [
    `import type { IOMainModulePart } from '../../../shared/types'` // Path from generated modules.main.ts to shared/types.ts
]
let mainRegistryHandlersArray = []
let moduleIdsForSharedType = [];
let moduleIdsForSharedConst = [];

try {
    const moduleDirs = fs.readdirSync(rendererModulesBaseDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name)

    for (const moduleName of moduleDirs) {
        // --- Check for Renderer Module File ---
        const rendererModuleSourceFile = path.join(rendererModulesBaseDir, moduleName, `${moduleName}.tsx`)
        const rendererModuleFileForImport = `./${moduleName}/${moduleName}`

        if (fs.existsSync(rendererModuleSourceFile)) {
            const moduleVarName = `${moduleName.toLowerCase().replace(/-/g, '')}Module`
            const moduleIdString = `${moduleName.toLowerCase()}-module`
            rendererImportsArray.push(`import * as ${moduleVarName} from '${rendererModuleFileForImport}'`)
            // We rely on each .tsx module exporting an 'id'
            rendererExportsArray.push(`  [${moduleVarName}.id]: ${moduleVarName}`)
            
            moduleIdsForSharedType.push(`  | '${moduleIdString}'`); // Add to type union
            moduleIdsForSharedConst.push(`  '${moduleIdString}'`);   // Add to const array

            // --- Check for corresponding Main Process Logic File ---
            const mainLogicSourceFile = path.join(rendererModulesBaseDir, moduleName, `${moduleName}.main.ts`)
            const mainLogicFileForImport = `./${moduleName}/${moduleName}.main`

            if (fs.existsSync(mainLogicSourceFile)) {
                const mainModuleVarName = `${moduleName.toLowerCase().replace(/-/g, '')}Main`
                // Assumes ModuleName.main.ts default exports the IOMainModulePart compatible object
                if (moduleName.toLowerCase() === 'example') {
                    console.log("SYNC-MODULES: Skipping 'Example' module for production registries.");
                    continue; // Skip this directory
                }
                mainRegistryImportsArray.push(`import ${mainModuleVarName} from '${mainLogicFileForImport}'`)
                mainRegistryHandlersArray.push(`  ${mainModuleVarName}`)
            }
        } else {
            console.warn(`WW Sync-Modules: Skipped directory '${moduleName}' as it does not contain a '${moduleName}.tsx' file.`)
        }
    }

    // Construct renderer modules.ts content
    let rendererFileContent = "// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js\n\n"
    rendererFileContent += rendererImportsArray.join('\n') + (rendererImportsArray.length ? '' : '') + '\n\n'
    rendererFileContent += 'export default {\n'
    rendererFileContent += rendererExportsArray.join(',\n') +'\n'
    rendererFileContent += '}\n'
    fs.writeFileSync(rendererModulesRegistryPath, rendererFileContent)
    console.log(`✅ Generated Renderer Modules Registry: ${rendererModulesRegistryPath}`)

    // Construct main modules.main.ts content
    let mainFileContent = "// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js\n\n"
    mainFileContent += mainRegistryImportsArray.join('\n') + (mainRegistryImportsArray.length ? '' : '') + '\n\n'
    mainFileContent += 'export const mainModuleHandlers: IOMainModulePart[] = [\n'
    mainFileContent += mainRegistryHandlersArray.join(',\n') + '\n'
    mainFileContent += ']\n'
    fs.writeFileSync(mainProcessModulesRegistryPath, mainFileContent)
    console.log(`✅ Generated Main Process Modules Registry: ${mainProcessModulesRegistryPath}`)

    // NEW: Generate src/shared/module-ids.ts
    const sharedModuleIdsPath = path.join(__dirname, '../src/shared/module-ids.ts');
    let sharedModuleIdsContent = "// THIS FILE IS AUTO-GENERATED BY scripts/sync-modules.js\n\n";
    sharedModuleIdsContent += "export type ModuleId =\n" + moduleIdsForSharedType.join('\n') + '\n\n';
    sharedModuleIdsContent += "export const ALL_MODULE_IDS: ModuleId[] = [\n" + moduleIdsForSharedConst.join(',\n') + '\n]\n';
    fs.writeFileSync(sharedModuleIdsPath, sharedModuleIdsContent);
    console.log(`✅ Generated Shared Module IDs: ${sharedModuleIdsPath}`);

} catch (error) {
    console.error("❌ Error syncing modules:", error)
    process.exit(1)
}