name: Debug IO CI Environment

on:
  workflow_dispatch:
    inputs:
      build_macos_intel:
        description: 'Log env for macOS (Intel x64)'
        default: false
        type: boolean
      build_macos_arm64:
        description: 'Log env for macOS (ARM64/Silicon)'
        default: true
        type: boolean
      build_ubuntu:
        description: 'Log env for Ubuntu Linux (x64)'
        default: false
        type: boolean
      build_windows:
        description: 'Log env for Windows (x64)'
        default: false
        type: boolean

jobs:
  prepare_debug_matrix:
    name: Prepare Debug Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.set-matrix.outputs.matrix_json }}
    steps:
      - name: Check Inputs and Prepare Matrix JSON
        id: set-matrix
        shell: bash
        run: |
          matrix_include_array=()
          if [[ "${{ github.event.inputs.build_macos_intel }}" == "true" ]]; then
            matrix_include_array+=('{"os_id": "macos_intel", "os_name": "macOS Intel", "os_runner": "macos-13"}')
          fi
          if [[ "${{ github.event.inputs.build_macos_arm64 }}" == "true" ]]; then
            matrix_include_array+=('{"os_id": "macos_arm64", "os_name": "macOS ARM64", "os_runner": "macos-14"}')
          fi
          if [[ "${{ github.event.inputs.build_ubuntu }}" == "true" ]]; then
            matrix_include_array+=('{"os_id": "linux", "os_name": "Ubuntu Linux", "os_runner": "ubuntu-latest"}')
          fi
          if [[ "${{ github.event.inputs.build_windows }}" == "true" ]]; then
            matrix_include_array+=('{"os_id": "windows", "os_name": "Windows", "os_runner": "windows-latest"}')
          fi
          
          joined_includes=$(IFS=,; echo "${matrix_include_array[*]}")
          final_matrix_json="{\"include\": [${joined_includes}]}"
          
          echo "Generated matrix JSON: ${final_matrix_json}"
          echo "matrix_json=${final_matrix_json}" >> $GITHUB_OUTPUT

  debug_environment:
    name: Debug Environment (${{ matrix.os_name }})
    needs: prepare_debug_matrix
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare_debug_matrix.outputs.matrix_json) }}
            
    env:
      NODE_VERSION: '22.x'
      PYTHON_VERSION: '3.12'

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Log Initial System & Environment Info (${{ matrix.os_name }})
        shell: bash
        run: |
          echo "================== INITIAL INFO (${{ matrix.os_name }}) =================="
          echo "Runner OS: $(uname -a || ver)"
          echo "Node version: $(node --version)"
          echo "Python3 version: $(python3 --version 2>&1 || echo 'python3 not found')"
          echo "--- C/C++ Compiler Info ---"
          if [[ "${{ matrix.os_id }}" == "macos_intel" || "${{ matrix.os_id }}" == "macos_arm64" ]]; then
            echo "Clang version: $(clang --version || echo 'clang not found')"
            echo "Xcode version: $(xcodebuild -version || echo 'xcodebuild not found')"
            echo "SDK Path: $(xcrun --sdk macosx --show-sdk-path || echo 'SDK path not found')"
          elif [[ "${{ matrix.os_id }}" == "linux" ]]; then
            echo "gcc version: $(gcc --version || echo 'gcc not found')"
          elif [[ "${{ matrix.os_id }}" == "windows" ]]; then
            where cl.exe || echo "cl.exe (MSVC compiler) not found in PATH"
          fi
          echo "--- Initial Key Environment Variables ---"
          echo "GYP_DEFINES: $GYP_DEFINES"
          echo "CXXFLAGS: $CXXFLAGS"
          echo "MACOSX_DEPLOYMENT_TARGET: $MACOSX_DEPLOYMENT_TARGET"
          printenv | sort
          echo "=========================================================="
      
      - name: Set C++ Build Envs for Rebuild (macOS only)
        if: matrix.os_id == 'macos_intel' || matrix.os_id == 'macos_arm64'
        shell: bash
        run: |
          echo "GYP_DEFINES=OS=mac mac_deployment_target=11.0 clang_cxx_language_standard=c++20 clang_cxx_library=libc++" >> $GITHUB_ENV
          echo "CXXFLAGS=-std=c++20 -stdlib=libc++ -mmacosx-version-min=11.0" >> $GITHUB_ENV
          echo "CFLAGS=-std=c17 -mmacosx-version-min=11.0" >> $GITHUB_ENV
          echo "LDFLAGS=-stdlib=libc++ -mmacosx-version-min=11.0" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV

      - name: Log Environment Info AFTER Setting Build Envs (macOS only)
        if: matrix.os_id == 'macos_intel' || matrix.os_id == 'macos_arm64'
        shell: bash
        run: |
          echo "================== POST-SET-ENVS INFO (${{ matrix.os_name }}) ================"
          echo "--- Key Environment Variables (After Setting via GITHUB_ENV) ---"
          echo "GYP_DEFINES: $GYP_DEFINES"
          echo "CXXFLAGS: $CXXFLAGS"
          echo "CFLAGS: $CFLAGS"
          echo "LDFLAGS: $LDFLAGS"
          echo "MACOSX_DEPLOYMENT_TARGET: $MACOSX_DEPLOYMENT_TARGET"
          printenv | sort
          echo "=========================================================="