name: Create Web Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    if: "startsWith(github.event.head_commit.message, 'web:')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: yarn

      - name: Build project
        run: GHPAGES=TRUE yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist/renderer

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist/renderer

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/renderer

      - name: Send Discord-Message
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  discord:
    name: Discord OnWebRelease
    needs: deploy
    if: "startsWith(github.event.head_commit.message, 'web:')"
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord-Message
        if: env.DISCORD_WEBHOOK != null
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        with:
          args: |
            New Web Release
            [IO](https://yeonv.github.io/io/)
