name: Create Web Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web App
    if: "startsWith(github.event.head_commit.message, 'web:')" # Trigger on commit messages starting with 'web:'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated
        with:
          node-version: 20.x # Recommended: Use a current LTS like 18.x or 20.x
          cache: 'yarn' # Enable caching for yarn dependencies

      - name: Install Linux dependencies for robotjs
        run: |
          sudo apt-get update
          sudo apt-get install -y libxtst-dev libpng++-dev libx11-dev libxkbfile-dev libsecret-1-dev build-essential python3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project for GitHub Pages
        env:
          # This env var is used by your build script to set the correct base path for Vite
          # Ensure your vite.config.ts or build script uses this.
          # Example: base: process.env.GHPAGES === 'TRUE' ? '/io/' : '/'
          GHPAGES: 'TRUE' 
        run: yarn build && ls -la # Assumes your build script handles output to ./dist/renderer

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Updated
        with:
          name: production-web-files # More specific name
          path: ./out/renderer # Path to your web build output

  deploy:
    name: Deploy to GitHub Pages
    needs: build # Depends on the build job completing successfully
    runs-on: ubuntu-latest
    # This job will only run if the build job ran (due to 'web:' commit) AND it's a push to the main branch.
    # The 'if' condition from the build job implicitly carries over because of 'needs'.
    # If you want to be extra explicit or have different conditions for deploy:
    if: "github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'web:')"

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # Updated
        with:
          name: production-web-files # Must match the upload name
          path: ./dist/renderer # Download to the same path structure expected by gh-pages action

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4 # Updated to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/renderer
          # Optional: add user_name and user_email if needed for commit attribution
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # Optional: commit_message: 'Deploy web release to GitHub Pages'

  notify_discord: # Renamed job for clarity
    name: Notify Discord of Web Release
    needs: deploy # Depends on successful deployment
    runs-on: ubuntu-latest
    # This job will only run if deploy job ran (due to 'web:' commit and main branch)
    if: "github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'web:') && success()" # success() ensures deploy job was successful

    steps:
      - name: Send Discord Release Message
        uses: Ilshidur/action-discord@0.3.2 # This action is a bit old, consider alternatives if issues arise
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }} # Use the specific release webhook
        with:
          args: |
            🚀 New IO Web Version Deployed! 🚀
            Access it here: https://yeonv.github.io/io/
            Commit: `${{ github.event.head_commit.message }}`